//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contratista
    {
        public string nombre { get; set; }
        public string apellido { get; set; }
        public int legajo { get; set; }
        public int dni { get; set; }
        public string cuil { get; set; }
        public string email { get; set; }
        public string celular { get; set; }
        public int idEmpresa { get; set; }
        public int idUsuario { get; set; }

        public string userName { get; set; }
        public string password { get; set; }
        public string status { get; set; }
        public string superSu { get; set; }

        /*
                public Contratista() {
                    Empresas = new Empresas();
                    usuario = new usuario();
                        }
                        */
        public Empresas Empresas { get; set; }
        public usuario usuario { get; set; }

    }
}
